WEATHER/WEATHER/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather_app.urls')),
    path('accounts/', include('accounts.urls')),
]

WEATHER/accounts/urls.py
__author__ = 'DELL'
from django.conf.urls import url
from .import views
from django.urls import path

app_name = "accounts"

urlpatterns = [
       path('register/',views.register_view,name='register'),
       path('login/',views.login_view,name='login'),
       path('logout/',views.logout_view,name='logout'),
       path('signup/',views.signup,name='signup'),
       url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

WEATHER/weather_app/urls.py
__author__ = 'DELL'
from django.urls import path
from .import views

app_name ="weather_app"
urlpatterns = [

    path('', views.sample, name='sample'),
    path('index', views.index, name='index'),
    path('forecast',views.forecast,name='forecast'),
    path('graph',views.data,name="data"),
    path('notify',views.notify,name='notify'),


]

WEATHER/weather_app/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural ='cities'


class Place(models.Model):
    place= models.CharField(max_length=25)

    def __str__(self):
        return self.place



class Data(models.Model):
    city=models.CharField(max_length=25)
    temp= models.IntegerField(blank=True,null=True)
    date=models.CharField(max_length=20,blank=True,null=True)
    def __str__(self):
        return self.city

WEATHER/weather_app/forms.py
__author__ = 'DELL'
from  django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm , TextInput
from .models import City ,Place, Data



class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets= {'name':TextInput(attrs={'class': "input" ,'placeholder': "City Name"})}





class PlaceForm(ModelForm):
    choices=[('Las Vegas','Las Vegas'),('Punjab','Punjab'),('Sacramento','Sacramento')]
    place= forms.CharField(label='Place',widget=forms.Select(choices=choices))
    class Meta:
        model =Place
        fields = ['place']

class DataForm(ModelForm):
    city=forms.CharField()
    class Meta:
        model= Data
        fields=['city']

WEATHER/weather_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate , login, logout
from django.views.generic import View
from .forms import  CityForm, PlaceForm ,DataForm
from .models import City,Place,Data
from django.shortcuts import  render, redirect
from django.contrib.auth.forms import AuthenticationForm

import jsonpickle,json
import serializers
import requests


def index(request):
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=a848cab9299c77d2d845b7bbf1d306b5'
    if request.method == 'POST':
        form = CityForm(request.POST)
        form.save()
    form = CityForm()
    cities= City.objects.all()
    weather_data=[]
    for city in cities:

        r = requests.get(url.format(city)).json()

        city_weather={
            'city':city.name,
            'temperature':r['main']['temp'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],

        }
        weather_data.append(city_weather)
    context = {'weather_data': weather_data, 'form': form}
    return render(request, 'weather_app/index.html',context)

def sample(request):
    return render(request,'weather_app/sample.html')

def forecast(request):
    url='https://api.openweathermap.org/data/2.5/forecast?q={}&units=imperial&appid=a848cab9299c77d2d845b7bbf1d306b5'


    if request.method=='POST':
        f1 = PlaceForm(request.POST)
        if f1.is_valid():
            f1.save()

        place= Place.objects.all()


        for p in place:
            rp = requests.get(url.format(p)).json()

            place_forecast={

            'temp_min':rp['list'][0]['main']['temp_min'],
            'temp_max':rp['list'][0]['main']['temp_max']
            }
            context={'place_forecast':place_forecast,'f1':f1}
            return render(request,'weather_app/sample.html',context)

    else:
        f1 = PlaceForm()
        return render(request,'weather_app/sample.html',{'f1':f1})


def data(request):

    url='https://api.openweathermap.org/data/2.5/forecast?q={}&units=imperial&appid=a848cab9299c77d2d845b7bbf1d306b5'

    if request.method =='GET':
        f2 = DataForm()
        return render(request,'weather_app/sample.html',{'f2':f2})
    else:
        f2 = DataForm(request.POST)
        f2.save()

        data=[]

        c=Data.objects.count()
        city= Data.objects.filter(id=c)

        for city in city:
            rps = requests.get(url.format(city)).json()
            for i in rps['list']:
                print(i['main']['temp'])
                data.append(i['main']['temp'])


        context ={'data':data}


        return render(request, 'weather_app/chart.html',context)


def notify(request):
    user= request.user
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=a848cab9299c77d2d845b7bbf1d306b5'
    r = requests.get(url.format('Mumbai')).json()

    if request.method=='GET':
        if request.user.is_authenticated:

            parameter={
                 'description':r['weather'][0]['description'],

                'user':user,
                'icon': r['weather'][0]['icon']

            }
            p= json.dumps({
                 'description':r['weather'][0]['description'],


                'icon': r['weather'][0]['icon']

            })
            return render(request,'weather_app/sample.html',{'p':p})
        else:

            parameter={

                'description':"Please register or login first",
                'icon': r['weather'][0]['icon']
                }

            return render(request,'weather_app/sample.html',parameter)

WEATHER/weather_app/templates/weather_app/chart.html
<!DOCTYPE html>
<html>
  <head>
    <title>Temperature Graph</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <link rel="stylesheet" type="text/css" href="weather_app/style.css">
  </head>
  <body>
    <div class="wrapper">
      <h1>TEMPERATURE GRAPH</h1>
        <div width="200" height="200">
    <canvas id="myChart" width="200" height="200"></canvas>
    </div>
        </div>

    <script >
        // Our labels along the x-axis
var years = [1,2,3,4,5,6,7,8];
// For drawing the lines
var content ={{data}};

var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: years,
    datasets: [

        {
            data : content,
            label: "Temperature",
            borderColor: "#3e95cd",
            fill: false
        }
    ]
  }
});

    </script>
  </body>
</html>

WEATHER/weather_app/templates/weather_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">

                                {{ form.name }}
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-info" >
                                    Add City
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for city_weather in weather_data %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ city_weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ city_weather.temperature }}° F</span>
                                        <br> {{ city_weather.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>

</html>

WEATHER/weather_app/templates/weather_app/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
      .dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #ddd}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}

    #a1{

        position: absolute;
        left:0;
        top:0;
        z-index: 1000;
        width: 500px;
        height: 50px;

        opacity: .8;

      }

  </style>



</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WEATHER APP</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

        <li><a href="#">USER</a></li>

        <li><a href="{% url 'weather_app:notify' %}">NOTIFICATION</a></li>


      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-log-in"></span> REGISTER</a></li>
        <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> LOGIN</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-in"></span> LOGOUT</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="{% url 'weather_app:forecast' %}">FORECAST</a></p>
      <p><a href="{% url 'weather_app:data' %}">GRAPH</a></p>
      <p><a href="{% url 'weather_app:index' %}">ADD MORE CITIES</a></p>
    </div>

      <!--------------------------------------------------------------------------------------------------------------------------------->

    <div class="col-sm-8 text-left"  id = "c1" >
      <h1>Forecast</h1>
        <form  method="post">
            {% csrf_token %}
            {{ f1 }}
            <input type="submit" value="Select">
        </form>




        <h2>Day Forecast</h2>
        <h3>Min</h3><label >{{ place_forecast.temp_min }}</label>
        <h3>Max</h3><label>{{ place_forecast.temp_max }}</label>

      <hr>

    </div>
     <div class="col-sm-8 text-left"  id = "c2">
      <h1>Graph</h1>



         <form method="post" enctype="multipart/form-data">
             {% csrf_token %}

             {% for field in f2 %}
             <div>{{ field }}</div>
             {% endfor %}
            <button type="submit" >Submit</button>

        </form>

      <hr>
     </div>
      </div>
    </div>
   <!-- <div class="col-sm-2 sidenav">

    </div>-->
  </div>
</div>



<div  id="a1" class="alert alert-info alert-dismissible fade in">


  </div>


<script>

    $(document).ready(function(){
        var p={};



            if(top.location.pathname==='/notify') {

                console.log({{ p|safe }});
                var my_var_parsed ='{{ p|safe }}';
                //console.log(my_var_parsed.description);

                my_var_parsed=JSON.parse(my_var_parsed);
                $("#a1").text(my_var_parsed.description).append('<a  href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>');

            }
            else{
                var x = document.getElementById("a1");
                x.style.display="none";
        }



});
</script>


<footer class="container-fluid text-center">
  <p>THANK YOU</p>
</footer>

</body>
</html>